def title():
  print ('Alabama 2015:')
  print ('SEC Champs')
  print('')
  start()
def start():
  game = int(input('What game: '))
  print('')
  if game == 1:
   print ('Alabama 35 Wisconsin 17')
   print ('-----------Wisconsin-----------Bama-----------')
   print ('First downs:  17                27            ')
   print ('Total Yrds:   268               502           ')
   print ('Passing:      228               264           ')
   print ('  C-A-I:    26-39-1            22-29-0        ')  
   print ('Rushing:      40                238           ')
   print ('  Att:        21                 37           ')
   print('')
   start()
  if game == 2:
   print ('Alabama 37 Middle Tennessee 10')
   print ('-------------MTSU-------------Bama-------------')
   print ('First downs:  15               28              ')
   print ('Total Yrds:   275              532             ')
   print ('Passing:      189              312             ')
   print ('  C-A-I:    23-43-1          26-43-2           ')  
   print ('Rushing:      86               220             ')
   print ('  Att:        31               39              ')
   print('')
   start()
  if game == 3:
   print ('Alabama 37 Ole Miss 43')
   print ('--------------Ole Miss------------Bama---------')
   print ('First downs:     16                29          ')
   print ('Total Yrds:      433               503         ')
   print ('Passing:         341               288         ')
   print ('  C-A-I:       18-33-0           32-59-3       ')  
   print ('Rushing:         92                215         ')
   print ('  Att:           32                42          ')
   print('')
   start()
title()
